# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sales_record.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12sales_record.proto\"\x0f\n\rEmptyMesssage\")\n\x17SalesRecordPingResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"#\n\x13SalesRecordResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0ePayloadRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x82\x01\n\x12SalesRecordRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x12\n\nunits_sold\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\t\x12\x11\n\tunit_cost\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t2\x8c\x02\n\x0bSalesRecord\x12<\n\x10PingSalesRecords\x12\x0e.EmptyMesssage\x1a\x18.SalesRecordPingResponse\x12=\n\x10SendSalesRecords\x12\x13.SalesRecordRequest\x1a\x14.SalesRecordResponse\x12\x39\n\x10SendSalesPayload\x12\x0f.PayloadRequest\x1a\x14.SalesRecordResponse\x12\x45\n\x16SendSalesRecordsStream\x12\x13.SalesRecordRequest\x1a\x14.SalesRecordResponse(\x01\x62\x06proto3'
)




_EMPTYMESSSAGE = _descriptor.Descriptor(
  name='EmptyMesssage',
  full_name='EmptyMesssage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=37,
)


_SALESRECORDPINGRESPONSE = _descriptor.Descriptor(
  name='SalesRecordPingResponse',
  full_name='SalesRecordPingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SalesRecordPingResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=80,
)


_SALESRECORDRESPONSE = _descriptor.Descriptor(
  name='SalesRecordResponse',
  full_name='SalesRecordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SalesRecordResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=117,
)


_PAYLOADREQUEST = _descriptor.Descriptor(
  name='PayloadRequest',
  full_name='PayloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='PayloadRequest.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=152,
)


_SALESRECORDREQUEST = _descriptor.Descriptor(
  name='SalesRecordRequest',
  full_name='SalesRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='SalesRecordRequest.region', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='SalesRecordRequest.item_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='units_sold', full_name='SalesRecordRequest.units_sold', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit_price', full_name='SalesRecordRequest.unit_price', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit_cost', full_name='SalesRecordRequest.unit_cost', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='SalesRecordRequest.source', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=285,
)

DESCRIPTOR.message_types_by_name['EmptyMesssage'] = _EMPTYMESSSAGE
DESCRIPTOR.message_types_by_name['SalesRecordPingResponse'] = _SALESRECORDPINGRESPONSE
DESCRIPTOR.message_types_by_name['SalesRecordResponse'] = _SALESRECORDRESPONSE
DESCRIPTOR.message_types_by_name['PayloadRequest'] = _PAYLOADREQUEST
DESCRIPTOR.message_types_by_name['SalesRecordRequest'] = _SALESRECORDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMesssage = _reflection.GeneratedProtocolMessageType('EmptyMesssage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSSAGE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMesssage)
  })
_sym_db.RegisterMessage(EmptyMesssage)

SalesRecordPingResponse = _reflection.GeneratedProtocolMessageType('SalesRecordPingResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDPINGRESPONSE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordPingResponse)
  })
_sym_db.RegisterMessage(SalesRecordPingResponse)

SalesRecordResponse = _reflection.GeneratedProtocolMessageType('SalesRecordResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDRESPONSE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordResponse)
  })
_sym_db.RegisterMessage(SalesRecordResponse)

PayloadRequest = _reflection.GeneratedProtocolMessageType('PayloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADREQUEST,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:PayloadRequest)
  })
_sym_db.RegisterMessage(PayloadRequest)

SalesRecordRequest = _reflection.GeneratedProtocolMessageType('SalesRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDREQUEST,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordRequest)
  })
_sym_db.RegisterMessage(SalesRecordRequest)



_SALESRECORD = _descriptor.ServiceDescriptor(
  name='SalesRecord',
  full_name='SalesRecord',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=288,
  serialized_end=556,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingSalesRecords',
    full_name='SalesRecord.PingSalesRecords',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSSAGE,
    output_type=_SALESRECORDPINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendSalesRecords',
    full_name='SalesRecord.SendSalesRecords',
    index=1,
    containing_service=None,
    input_type=_SALESRECORDREQUEST,
    output_type=_SALESRECORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendSalesPayload',
    full_name='SalesRecord.SendSalesPayload',
    index=2,
    containing_service=None,
    input_type=_PAYLOADREQUEST,
    output_type=_SALESRECORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendSalesRecordsStream',
    full_name='SalesRecord.SendSalesRecordsStream',
    index=3,
    containing_service=None,
    input_type=_SALESRECORDREQUEST,
    output_type=_SALESRECORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SALESRECORD)

DESCRIPTOR.services_by_name['SalesRecord'] = _SALESRECORD

# @@protoc_insertion_point(module_scope)
