version: '3.3'
services:    
    srv_persistor:
        build: 
            context: ./
            
            dockerfile: ./srv_persistor/Dockerfile
        ports:
            - "50051:50051"
        depends_on:
            - mongo
    srv_reader:
        build: 
            context: ./
            dockerfile: ./srv_reader/Dockerfile
        environment:
            - DIR_FILE=/tmp/data/100000_sr.csv
        depends_on: 
            - srv_persistor
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
        depends_on:
            - mongo